export const user = [
  {
    username: "user123",
    password: "userpassword",
    usertype: "user",
    cart: [
      {
        id: 0,
        itemName: "Nike Jordan V1",
        sizes: ["small", "medium", "large"],
        price: 100,
        quantity: 100,
        brand: "Nike",
      },
    ],
  },
  {
    username: "admin123",
    password: "adminpassword",
    userType: "admin",
  },
];

export const products = [
  {
    id: 0,
    itemName: "Nike Jordan V1",
    sizes: ["small", "medium", "large"],
    price: 100,
    quantity: 100,
    brand: "Nike",
  },
  {
    id: 1,
    itemName: "Nike Air Max 270",
    sizes: ["small", "medium", "large"],
    price: 130,
    quantity: 90,
    brand: "Nike",
  },
  {
    id: 2,
    itemName: "Adidas Ultraboost 22",
    sizes: ["medium", "large"],
    price: 120,
    quantity: 75,
    brand: "Adidas",
  },
  {
    id: 3,
    itemName: "Adidas NMD_R1",
    sizes: ["medium", "large"],
    price: 110,
    quantity: 140,
    brand: "Adidas",
  },
  {
    id: 4,
    itemName: "Puma RS-X3",
    sizes: ["small", "medium"],
    price: 90,
    quantity: 150,
    brand: "Puma",
  },
  {
    id: 5,
    itemName: "Puma Future Rider",
    sizes: ["small", "medium", "large"],
    price: 100,
    quantity: 120,
    brand: "Puma",
  },
  {
    id: 6,
    itemName: "Vans Old Skool",
    sizes: ["small", "medium", "large"],
    price: 65,
    quantity: 180,
    brand: "Vans",
  },
  {
    id: 7,
    itemName: "Vans Authentic",
    sizes: ["small", "medium"],
    price: 55,
    quantity: 250,
    brand: "Vans",
  },
  {
    id: 8,
    itemName: "Skechers Go Walk",
    sizes: ["small", "medium", "large"],
    price: 55,
    quantity: 250,
    brand: "Skechers",
  },
  {
    id: 9,
    itemName: "Fila Disruptor 2",
    sizes: ["medium", "large"],
    price: 75,
    quantity: 95,
    brand: "Fila",
  },
  {
    id: 10,
    itemName: "Saucony Endorphin Speed",
    sizes: ["small", "medium"],
    price: 140,
    quantity: 110,
    brand: "Saucony",
  },
  {
    id: 11,
    itemName: "Asics Gel-Kayano 27",
    sizes: ["small", "medium"],
    price: 160,
    quantity: 60,
    brand: "Asics",
  },
];
