export const user = [
  {
    email: "user123@gmail.com",
    username: "user123",
    password: "userpassword",
    usertype: "user",
    cart: [],
  },
  {
    email: "jeremy123@gmail.com",
    username: "jeremy",
    password: "jeremy123",
    usertype: "user",
    cart: [],
  },
  {
    username: "admin123",
    password: "adminpassword",
    userType: "admin",
  },
];

export const products = [
  // Nike
  {
    id: 0,
    itemName: "Nike Jordan V1",
    sizes: ["small", "medium", "large"],
    price: 100,
    quantity: 100,
    brand: "Nike",
    ratingCount: 250,
  },
  {
    id: 1,
    itemName: "Nike Air Max 270",
    sizes: ["small", "medium", "large"],
    price: 130,
    quantity: 90,
    brand: "Nike",
    ratingCount: 210,
  },
  {
    id: 2,
    itemName: "Nike Air Zoom Pegasus 37",
    sizes: ["small", "medium", "large"],
    price: 120,
    quantity: 80,
    brand: "Nike",
    ratingCount: 180,
  },
  {
    id: 3,
    itemName: "Nike React Infinity Run Flyknit",
    sizes: ["small", "medium", "large"],
    price: 150,
    quantity: 70,
    brand: "Nike",
    ratingCount: 200,
  },
  {
    id: 4,
    itemName: "Nike Free RN 5.0",
    sizes: ["small", "medium", "large"],
    price: 110,
    quantity: 90,
    brand: "Nike",
    ratingCount: 220,
  },

  // Adidas
  {
    id: 5,
    itemName: "Adidas Ultraboost 22",
    sizes: ["medium", "large"],
    price: 120,
    quantity: 75,
    brand: "Adidas",
    ratingCount: 180,
  },
  {
    id: 6,
    itemName: "Adidas NMD_R1",
    sizes: ["medium", "large"],
    price: 110,
    quantity: 140,
    brand: "Adidas",
    ratingCount: 220,
  },
  {
    id: 7,
    itemName: "Adidas Yeezy Boost 350",
    sizes: ["medium", "large"],
    price: 220,
    quantity: 50,
    brand: "Adidas",
    ratingCount: 150,
  },
  {
    id: 8,
    itemName: "Adidas Stan Smith",
    sizes: ["small", "medium", "large"],
    price: 85,
    quantity: 100,
    brand: "Adidas",
    ratingCount: 270,
  },
  {
    id: 9,
    itemName: "Adidas Gazelle",
    sizes: ["medium", "large"],
    price: 100,
    quantity: 90,
    brand: "Adidas",
    ratingCount: 160,
  },

  // Puma
  {
    id: 10,
    itemName: "Puma RS-X3",
    sizes: ["small", "medium"],
    price: 90,
    quantity: 150,
    brand: "Puma",
    ratingCount: 150,
  },
  {
    id: 11,
    itemName: "Puma Future Rider",
    sizes: ["small", "medium", "large"],
    price: 100,
    quantity: 120,
    brand: "Puma",
    ratingCount: 190,
  },
  {
    id: 12,
    itemName: "Puma Suede Classic",
    sizes: ["small", "medium"],
    price: 70,
    quantity: 160,
    brand: "Puma",
    ratingCount: 300,
  },
  {
    id: 13,
    itemName: "Puma Clyde Court",
    sizes: ["medium", "large"],
    price: 120,
    quantity: 130,
    brand: "Puma",
    ratingCount: 110,
  },
  {
    id: 14,
    itemName: "Puma Cali Sport",
    sizes: ["small", "medium"],
    price: 85,
    quantity: 140,
    brand: "Puma",
    ratingCount: 210,
  },

  // Vans
  {
    id: 15,
    itemName: "Vans Old Skool",
    sizes: ["small", "medium", "large"],
    price: 65,
    quantity: 180,
    brand: "Vans",
    ratingCount: 300,
  },
  {
    id: 16,
    itemName: "Vans Authentic",
    sizes: ["small", "medium"],
    price: 55,
    quantity: 250,
    brand: "Vans",
    ratingCount: 400,
  },
  {
    id: 17,
    itemName: "Vans Sk8-Hi",
    sizes: ["small", "medium", "large"],
    price: 75,
    quantity: 100,
    brand: "Vans",
    ratingCount: 270,
  },
  {
    id: 18,
    itemName: "Vans Era",
    sizes: ["medium", "large"],
    price: 60,
    quantity: 140,
    brand: "Vans",
    ratingCount: 250,
  },
  {
    id: 19,
    itemName: "Vans Slip-On",
    sizes: ["small", "medium"],
    price: 50,
    quantity: 210,
    brand: "Vans",
    ratingCount: 320,
  },

  // Skechers
  {
    id: 20,
    itemName: "Skechers Go Walk",
    sizes: ["small", "medium", "large"],
    price: 55,
    quantity: 250,
    brand: "Skechers",
    ratingCount: 350,
  },
  {
    id: 21,
    itemName: "Skechers D'lites",
    sizes: ["small", "medium"],
    price: 65,
    quantity: 180,
    brand: "Skechers",
    ratingCount: 280,
  },
  {
    id: 22,
    itemName: "Skechers Energy Lights",
    sizes: ["medium", "large"],
    price: 80,
    quantity: 150,
    brand: "Skechers",
    ratingCount: 230,
  },
  {
    id: 23,
    itemName: "Skechers Arch Fit",
    sizes: ["small", "medium", "large"],
    price: 90,
    quantity: 120,
    brand: "Skechers",
    ratingCount: 200,
  },
  {
    id: 24,
    itemName: "Skechers On-the-Go",
    sizes: ["small", "medium"],
    price: 70,
    quantity: 160,
    brand: "Skechers",
    ratingCount: 270,
  },

  // Fila
  {
    id: 25,
    itemName: "Fila Disruptor 2",
    sizes: ["medium", "large"],
    price: 75,
    quantity: 95,
    brand: "Fila",
    ratingCount: 160,
  },
  {
    id: 26,
    itemName: "Fila Ray Tracer",
    sizes: ["small", "medium"],
    price: 85,
    quantity: 100,
    brand: "Fila",
    ratingCount: 190,
  },
  {
    id: 27,
    itemName: "Fila Original Fitness",
    sizes: ["medium", "large"],
    price: 80,
    quantity: 120,
    brand: "Fila",
    ratingCount: 230,
  },
  {
    id: 28,
    itemName: "Fila Venom",
    sizes: ["small", "medium"],
    price: 95,
    quantity: 110,
    brand: "Fila",
    ratingCount: 180,
  },
  {
    id: 29,
    itemName: "Fila Disruptor 3",
    sizes: ["medium", "large"],
    price: 85,
    quantity: 90,
    brand: "Fila",
    ratingCount: 200,
  },
];
